services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: |
      pip install -r requirements.txt  # Install yt-dlp
      npm install                      # Install Node.js dependencies
    startCommand: node index.js
    envVars:
      - key: PYTHON_VERSION
        value: 3.9  # (or another supported Python version)
